### PR TITLE
Fix pseudo class matching

### PR DESCRIPTION
**Pull request by ktslwy**
Found an issue when using certain pseudo classes. For example, in the pseudo class regex the `:l` comes before the `:li` and the regex doesn't check if there are more characters after. So using `:li` gets matched with `:left`. Adding a negative lookahead check to make sure the full string is read. The test case can reproduce the issue without the fix.

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by ktslwy** [comment]
CLA signed

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by renatoi** [comment]
Thanks! Looks good to me.

**Pull request merged**
