### PR TITLE
Removing unused options

### PR DESCRIPTION
**Pull request by src-code**
Addressing issue #94.

### CODE REVIEW

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by renatoi** [comment]
We don't want to keep the minify there?

**Comment by src-code** [comment]
I don't think `minify` is actually doing anything right now.  So we could add it back if we added support.

**Comment by renatoi** [comment]
Keep it out for now then. Add it back if we think it's needed. LGTM.

**Comment by src-code** [comment]
@renatoi I'm wrong, minify *is* doing something.  Apparently it's an Absurd option.  Along with `keepCamelCase` and `combineSelectors`.  It looks like we're setting the same default values that Absurd uses... not sure what these options do, aside from `minify`, however.

**Comment by renatoi** [comment]
I'd say let's keep them out. Ideally combineSelectors and keepCameCase should be default in Atomizer. Minify could be an option, but not terribly necessary.

**Comment by src-code** [comment]
Ok, sounds good to me.

**Pull request merged**
