### PR TITLE
Remove keywords (issue #73)

### PR DESCRIPTION
**Pull request by thierryk**
@yasteve @renatoi  I also removed `suffixType: 'numerical'` as I don't think this does anything, does it?

### CODE REVIEW

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by src-code** [comment]
`numerical` was for auto-incrementing suffixes... so if true, they're: 1,2,3..., and if false: a,b,c... 
By default Atomizer treats this param as 'false', so removing it would change the current behavior.  Not sure we intend to keep supporting this feature, however. @renatoi?

**Comment by src-code** [comment]
Addresses issue #73

**Comment by thierryk** [comment]
I put it back as I could imagine people willing to use `Fz1`, `Fz-2`, etc. After all, these should be considered sizes too.

**Comment by renatoi** [comment]
I think we should get rid of these since it can mess up with `allowSuffixToValue`, also encouraging a bad practice (because it can create issues).

Example: `Lh-1`, `Lh-2`: Are these valid values or a sequence?

Ideally, as a good practice, custom classes shouldn't have a numerical sequence.

**Comment by src-code** [comment]
LGTM.

**Pull request merged**
