### PR TITLE
Fixes #179

### LINKED ISSUE #179: Set different values to a variable depending on breakpoints
Imagine this:

```javascript
'custom': {
    '$columnWidth': '20px',
    '$gutter': {
        'sm': '10px',
        'md': '15px',
        'lg': '20px'
    }
}
``` 
Then in the markup:
```html
<div class="P($gutter)"></div>
```

The **same class** in the markup will create a different padding around the box depending on breakpoints. 
And changes are made via the config object &mdash; not via markup (same as if we were editing a rule in a style sheet).

### PR DESCRIPTION
**Pull request by renatoi**
@hankhsiao @thierryk

### CODE REVIEW

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by hankhsiao** [comment]
:+1:

**Comment by hankhsiao** [comment]
This is only for breakpoints, do we have it for context?

**Comment by renatoi** [comment]
We could also add it for context. I can implement that in a separate PR.

**Pull request merged**
