### PR TITLE
Add missing quotes around value of content property

### PR DESCRIPTION
**Pull request by thierryk**
@renatoi Karen spotted the issue of the missing pseudo-element this morning (she got "..." in the middle of strings).

### CODE REVIEW

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by kfay** [comment]
@thierryk it looks like there are a few more instances of "content" strings that probably also need this fix in this same file. (e.g. the one for `Ell:after`)

**Comment by thierryk** [comment]
Thanks @kfay &mdash; I took care of `Ell` and `Cf` too.

**Comment by kfay** [comment]
LGTM, thanks @thierryk !

**Pull request merged**
