### PR TITLE
Updating README for 2.0.0-beta

### PR DESCRIPTION
**Pull request by src-code**
Updates for 2.0.0-beta

@renatoi

### CODE REVIEW

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by renatoi** [comment]
I think we should add a link to grunt-atomizer somewhere in the README.

**Comment by renatoi** [comment]
Other than that, LGTM.

**Comment by src-code** [comment]
@renatoi Do you propose to link to any and all Atomizer-related packages that come along?  Eg, including 3rd-party authored projects, for instance if someone were to create plugins for other task runners?

**Comment by renatoi** [comment]
@src-code Yeah, I think it makes sense to have a link to all related tools for Atomizer.

**Comment by src-code** [comment]
Ok, let me add links in a new pull, so we don't have to hold up 2.0.0 any further!

**Pull request merged**
