### PR TITLE
Regex Fixes

### PR DESCRIPTION
**Pull request by renatoi**
@src-code @thierryk 

Fixed a problem with:

   * Helpers param Regex (I'm not proud of the solution though)
   * Parent selectors
   * Added sibling combinator
   * Added ability to have exclusive decimal number value. (e.g. `Trsdu-.3s` and `Op-.3`

### CODE REVIEW

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by src-code** [comment]
@renatoi What part of the helpers param regex aren't you happy with?

**Comment by renatoi** [comment]
@src-code It's actually a fix I had to include for the parent selector:

```
'PARENT'     : '[^\\s:>_\'"`]+',
```
I had to include `"`, `'` and `` ` `` to the negative character class. Basically, find any character that is not a space, colon, a parent separator, double quotes, single quotes, backtick. Do you have a better idea to match the parent selector?

**Comment by renatoi** [comment]
Maybe I shouldn't be that open and go more restrictive, making an assumption of the possible characters for a parent class name?

`[a-zA-Z][-_a-zA-Z0-9]+?`

**Comment by src-code** [comment]
@renatoi Yeah, I kind of like the idea of whitelisting instead of blacklisting there

**Pull request merged**
